# Generated by Django 3.2.25 on 2025-10-13 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_1', '0002_auto_20251006_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ('created_date',)},
        ),
    ]
