# Generated by Django 3.2.25 on 2025-10-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20251013_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='bllog/default.jpg', upload_to='blog'),
        ),
    ]
