# Generated by Django 3.2.25 on 2026-08-08 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_comment_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='appproved',
            new_name='approved',
        ),
    ]
